Fixed error multiple definition of `full_url'
From GCC 10 defaults option of `-fcommon` is changed to `-fno-common`. It will caused an error like below:

```
/usr/bin/ld: afpcmd-cmdline_main.o:/tmp/afpfs-ng-0.8.1/cmdline/cmdline_afp.h:4: multiple definition of `full_url'; afpcmd-cmdline_afp.o:/tmp/afpfs-ng-0.8.1/cmdline/cmdline_afp.c:27: first defined here
```